/**
 * Cultural Authenticity Preset Library
 * 
 * 50+ curated combinations of South African linguistic, regional, and rhythmic characteristics
 * organized by Amapiano subgenre for authentic music generation.
 */

export interface CulturalPreset {
  id: string;
  name: string;
  description: string;
  subgenre: 'soulful' | 'sgija' | 'bacardi' | 'private_school' | 'vocal' | 'deep' | 'experimental';
  language: string;
  region: string;
  gaspType: string;
  gaspIntensity: string;
  tags: string[];
  popularity: number; // 1-5 stars
}

export const CULTURAL_PRESETS: CulturalPreset[] = [
  // === SOULFUL AMAPIANO (Smooth, Jazz-influenced, Romantic) ===
  {
    id: 'soulful_gauteng_classic',
    name: 'Gauteng Soulful Classic',
    description: 'The quintessential Johannesburg sound - smooth, jazzy, romantic. Perfect for late-night drives.',
    subgenre: 'soulful',
    language: 'zulu',
    region: 'gauteng_jhb',
    gaspType: 'classic',
    gaspIntensity: 'moderate',
    tags: ['romantic', 'smooth', 'jazzy', 'classic'],
    popularity: 5,
  },
  {
    id: 'soulful_pretoria_gospel',
    name: 'Pretoria Gospel Soulful',
    description: 'Gospel-influenced Pretoria style with tighter swing and spiritual undertones.',
    subgenre: 'soulful',
    language: 'sotho_north',
    region: 'gauteng_pretoria',
    gaspType: 'half_bar',
    gaspIntensity: 'light',
    tags: ['gospel', 'spiritual', 'uplifting'],
    popularity: 4,
  },
  {
    id: 'soulful_eastern_cape_xhosa',
    name: 'Eastern Cape Xhosa Soulful',
    description: 'Xhosa click consonants meet soulful piano - deeply cultural and emotional.',
    subgenre: 'soulful',
    language: 'xhosa',
    region: 'eastern_cape',
    gaspType: 'echo',
    gaspIntensity: 'moderate',
    tags: ['cultural', 'emotional', 'xhosa', 'clicks'],
    popularity: 4,
  },
  {
    id: 'soulful_limpopo_traditional',
    name: 'Limpopo Traditional Soulful',
    description: 'Slowest swing (60%) with deep traditional roots - meditative and grounding.',
    subgenre: 'soulful',
    language: 'venda',
    region: 'limpopo',
    gaspType: 'progressive',
    gaspIntensity: 'subtle',
    tags: ['traditional', 'meditative', 'slow', 'venda'],
    popularity: 3,
  },
  {
    id: 'soulful_free_state_balanced',
    name: 'Free State Balanced Soulful',
    description: 'Central SA style - perfectly balanced swing and groove for universal appeal.',
    subgenre: 'soulful',
    language: 'sotho_south',
    region: 'free_state',
    gaspType: 'selective',
    gaspIntensity: 'moderate',
    tags: ['balanced', 'universal', 'smooth'],
    popularity: 4,
  },

  // === SGIJA/BACARDI (High-energy, Dancefloor, Festival) ===
  {
    id: 'sgija_gauteng_double_gasp',
    name: 'Gauteng Sgija Double Gasp',
    description: 'High-energy JHB Sgija with double gasp - festival anthem material.',
    subgenre: 'sgija',
    language: 'zulu',
    region: 'gauteng_jhb',
    gaspType: 'double',
    gaspIntensity: 'full',
    tags: ['high-energy', 'festival', 'dancefloor', 'double-gasp'],
    popularity: 5,
  },
  {
    id: 'sgija_kzn_gqom_fusion',
    name: 'KZN Gqom-Sgija Fusion',
    description: 'Durban Gqom influence (52% swing) with stutter gasp - maximum intensity.',
    subgenre: 'sgija',
    language: 'zulu',
    region: 'kzn_durban',
    gaspType: 'stutter',
    gaspIntensity: 'heavy',
    tags: ['gqom', 'intense', 'durban', 'glitchy'],
    popularity: 5,
  },
  {
    id: 'bacardi_gauteng_buildup',
    name: 'Gauteng Bacardi Build-Up',
    description: 'Classic Bacardi style with build-up gasp for massive drops.',
    subgenre: 'bacardi',
    language: 'zulu',
    region: 'gauteng_jhb',
    gaspType: 'buildup',
    gaspIntensity: 'full',
    tags: ['bacardi', 'drop', 'festival', 'build-up'],
    popularity: 5,
  },
  {
    id: 'sgija_mpumalanga_rural',
    name: 'Mpumalanga Rural Sgija',
    description: 'Rural Mpumalanga style (59% swing) - loose groove with high energy.',
    subgenre: 'sgija',
    language: 'swazi',
    region: 'mpumalanga',
    gaspType: 'double',
    gaspIntensity: 'heavy',
    tags: ['rural', 'loose-groove', 'energetic'],
    popularity: 3,
  },
  {
    id: 'bacardi_pretoria_tight',
    name: 'Pretoria Tight Bacardi',
    description: 'Tighter Pretoria swing (57%) with full-bar gasp for dramatic effect.',
    subgenre: 'bacardi',
    language: 'tswana',
    region: 'gauteng_pretoria',
    gaspType: 'full_bar',
    gaspIntensity: 'full',
    tags: ['tight', 'dramatic', 'pretoria'],
    popularity: 4,
  },

  // === PRIVATE SCHOOL PIANO (Sophisticated, Melodic, Upscale) ===
  {
    id: 'private_school_gauteng_progressive',
    name: 'Gauteng Private School Progressive',
    description: 'Sophisticated JHB sound with progressive gasp - upscale and refined.',
    subgenre: 'private_school',
    language: 'english_sa',
    region: 'gauteng_jhb',
    gaspType: 'progressive',
    gaspIntensity: 'moderate',
    tags: ['sophisticated', 'upscale', 'melodic', 'refined'],
    popularity: 5,
  },
  {
    id: 'private_school_cape_town_house',
    name: 'Cape Town House-Piano Fusion',
    description: 'Western Cape house influence (50% straight) - sophisticated and modern.',
    subgenre: 'private_school',
    language: 'afrikaans',
    region: 'western_cape',
    gaspType: 'selective',
    gaspIntensity: 'light',
    tags: ['house', 'modern', 'cape-town', 'straight'],
    popularity: 4,
  },
  {
    id: 'private_school_pretoria_gospel',
    name: 'Pretoria Gospel Private School',
    description: 'Gospel-influenced upscale sound - spiritual sophistication.',
    subgenre: 'private_school',
    language: 'sotho_north',
    region: 'gauteng_pretoria',
    gaspType: 'echo',
    gaspIntensity: 'subtle',
    tags: ['gospel', 'spiritual', 'sophisticated'],
    popularity: 4,
  },
  {
    id: 'private_school_free_state_melodic',
    name: 'Free State Melodic Private School',
    description: 'Balanced central SA style with selective gasp - universally appealing.',
    subgenre: 'private_school',
    language: 'english_sa',
    region: 'free_state',
    gaspType: 'selective',
    gaspIntensity: 'moderate',
    tags: ['melodic', 'balanced', 'universal'],
    popularity: 4,
  },
  {
    id: 'private_school_eastern_cape_jazz',
    name: 'Eastern Cape Jazz Private School',
    description: 'Xhosa jazz fusion - sophisticated with cultural depth.',
    subgenre: 'private_school',
    language: 'xhosa',
    region: 'eastern_cape',
    gaspType: 'selective',
    gaspIntensity: 'light',
    tags: ['jazz', 'sophisticated', 'xhosa', 'fusion'],
    popularity: 3,
  },

  // === VOCAL AMAPIANO (Lyric-focused, Storytelling) ===
  {
    id: 'vocal_gauteng_zulu_love',
    name: 'Gauteng Zulu Love Song',
    description: 'Classic JHB sound with Zulu vocals - romantic storytelling.',
    subgenre: 'vocal',
    language: 'zulu',
    region: 'gauteng_jhb',
    gaspType: 'classic',
    gaspIntensity: 'moderate',
    tags: ['romantic', 'zulu', 'storytelling', 'love'],
    popularity: 5,
  },
  {
    id: 'vocal_eastern_cape_xhosa_anthem',
    name: 'Eastern Cape Xhosa Anthem',
    description: 'Powerful Xhosa vocals with click consonants - cultural pride.',
    subgenre: 'vocal',
    language: 'xhosa',
    region: 'eastern_cape',
    gaspType: 'half_bar',
    gaspIntensity: 'moderate',
    tags: ['xhosa', 'anthem', 'cultural', 'pride'],
    popularity: 4,
  },
  {
    id: 'vocal_limpopo_venda_spiritual',
    name: 'Limpopo Venda Spiritual',
    description: 'Venda tonal vocals with slowest swing - deeply spiritual.',
    subgenre: 'vocal',
    language: 'venda',
    region: 'limpopo',
    gaspType: 'echo',
    gaspIntensity: 'subtle',
    tags: ['venda', 'spiritual', 'tonal', 'meditative'],
    popularity: 3,
  },
  {
    id: 'vocal_kzn_zulu_party',
    name: 'KZN Zulu Party Anthem',
    description: 'Durban energy with Zulu party vocals - celebration vibes.',
    subgenre: 'vocal',
    language: 'zulu',
    region: 'kzn_durban',
    gaspType: 'double',
    gaspIntensity: 'heavy',
    tags: ['party', 'celebration', 'durban', 'energetic'],
    popularity: 5,
  },
  {
    id: 'vocal_pretoria_sotho_gospel',
    name: 'Pretoria Sotho Gospel',
    description: 'Gospel vocals in Sotho - uplifting and spiritual.',
    subgenre: 'vocal',
    language: 'sotho_north',
    region: 'gauteng_pretoria',
    gaspType: 'progressive',
    gaspIntensity: 'light',
    tags: ['gospel', 'sotho', 'uplifting', 'spiritual'],
    popularity: 4,
  },

  // === DEEP AMAPIANO (Minimal, Atmospheric, Introspective) ===
  {
    id: 'deep_gauteng_minimal',
    name: 'Gauteng Deep Minimal',
    description: 'Minimal JHB sound with reverse gasp - introspective and atmospheric.',
    subgenre: 'deep',
    language: 'english_sa',
    region: 'gauteng_jhb',
    gaspType: 'reverse',
    gaspIntensity: 'subtle',
    tags: ['minimal', 'atmospheric', 'introspective'],
    popularity: 4,
  },
  {
    id: 'deep_cape_town_house',
    name: 'Cape Town Deep House',
    description: 'Western Cape house influence - straight swing, deep atmosphere.',
    subgenre: 'deep',
    language: 'afrikaans',
    region: 'western_cape',
    gaspType: 'selective',
    gaspIntensity: 'subtle',
    tags: ['house', 'deep', 'atmospheric', 'cape-town'],
    popularity: 4,
  },
  {
    id: 'deep_northern_cape_desert',
    name: 'Northern Cape Desert Deep',
    description: 'Sparse Northern Cape style - desert minimalism.',
    subgenre: 'deep',
    language: 'afrikaans',
    region: 'northern_cape',
    gaspType: 'reverse',
    gaspIntensity: 'light',
    tags: ['sparse', 'minimal', 'desert', 'atmospheric'],
    popularity: 3,
  },
  {
    id: 'deep_limpopo_traditional',
    name: 'Limpopo Deep Traditional',
    description: 'Slowest swing with traditional Venda elements - meditative depth.',
    subgenre: 'deep',
    language: 'venda',
    region: 'limpopo',
    gaspType: 'echo',
    gaspIntensity: 'subtle',
    tags: ['traditional', 'meditative', 'venda', 'slow'],
    popularity: 3,
  },
  {
    id: 'deep_free_state_balanced',
    name: 'Free State Deep Balanced',
    description: 'Central SA deep sound - balanced and introspective.',
    subgenre: 'deep',
    language: 'sotho_south',
    region: 'free_state',
    gaspType: 'selective',
    gaspIntensity: 'moderate',
    tags: ['balanced', 'introspective', 'atmospheric'],
    popularity: 3,
  },

  // === EXPERIMENTAL (Boundary-pushing, Innovative) ===
  {
    id: 'experimental_gauteng_full_bar',
    name: 'Gauteng Experimental Full-Bar',
    description: 'Full-bar gasp with JHB swing - bold and experimental.',
    subgenre: 'experimental',
    language: 'english_sa',
    region: 'gauteng_jhb',
    gaspType: 'full_bar',
    gaspIntensity: 'full',
    tags: ['experimental', 'bold', 'innovative'],
    popularity: 3,
  },
  {
    id: 'experimental_kzn_gqom_fusion',
    name: 'KZN Gqom-Piano Fusion',
    description: 'Durban Gqom meets Amapiano - genre-bending innovation.',
    subgenre: 'experimental',
    language: 'zulu',
    region: 'kzn_durban',
    gaspType: 'stutter',
    gaspIntensity: 'full',
    tags: ['gqom', 'fusion', 'genre-bending', 'innovative'],
    popularity: 4,
  },
  {
    id: 'experimental_xhosa_clicks',
    name: 'Xhosa Click Percussion Experiment',
    description: 'Xhosa click consonants as percussion - cultural innovation.',
    subgenre: 'experimental',
    language: 'xhosa',
    region: 'eastern_cape',
    gaspType: 'stutter',
    gaspIntensity: 'heavy',
    tags: ['xhosa', 'clicks', 'percussion', 'innovative'],
    popularity: 3,
  },
  {
    id: 'experimental_venda_tonal',
    name: 'Venda Tonal Experiment',
    description: 'Venda 3-tone system mapped to melody - linguistic innovation.',
    subgenre: 'experimental',
    language: 'venda',
    region: 'limpopo',
    gaspType: 'progressive',
    gaspIntensity: 'moderate',
    tags: ['venda', 'tonal', 'melodic', 'linguistic'],
    popularity: 3,
  },
  {
    id: 'experimental_cape_town_straight',
    name: 'Cape Town Straight-Swing Experiment',
    description: 'Western Cape house (50% straight) - pushing Amapiano boundaries.',
    subgenre: 'experimental',
    language: 'afrikaans',
    region: 'western_cape',
    gaspType: 'reverse',
    gaspIntensity: 'heavy',
    tags: ['house', 'straight', 'boundary-pushing'],
    popularity: 3,
  },

  // === REGIONAL SHOWCASES (Highlighting specific regions) ===
  {
    id: 'regional_mpumalanga_rural',
    name: 'Mpumalanga Rural Showcase',
    description: 'Loosest swing (59%) with rural Swazi influence - authentic countryside.',
    subgenre: 'soulful',
    language: 'swazi',
    region: 'mpumalanga',
    gaspType: 'half_bar',
    gaspIntensity: 'moderate',
    tags: ['rural', 'swazi', 'countryside', 'loose-groove'],
    popularity: 3,
  },
  {
    id: 'regional_north_west_motswako',
    name: 'North West Motswako-Piano',
    description: 'Motswako hip-hop influence (56.5% swing) - rap meets piano.',
    subgenre: 'vocal',
    language: 'tswana',
    region: 'north_west',
    gaspType: 'classic',
    gaspIntensity: 'moderate',
    tags: ['motswako', 'hip-hop', 'rap', 'tswana'],
    popularity: 4,
  },
  {
    id: 'regional_northern_cape_sparse',
    name: 'Northern Cape Sparse Minimal',
    description: 'Sparsest style (54% swing) - desert minimalism.',
    subgenre: 'deep',
    language: 'afrikaans',
    region: 'northern_cape',
    gaspType: 'reverse',
    gaspIntensity: 'light',
    tags: ['sparse', 'minimal', 'desert'],
    popularity: 2,
  },
  {
    id: 'regional_eastern_cape_xhosa',
    name: 'Eastern Cape Xhosa Showcase',
    description: 'Xhosa cultural showcase - clicks, percussion, storytelling.',
    subgenre: 'vocal',
    language: 'xhosa',
    region: 'eastern_cape',
    gaspType: 'selective',
    gaspIntensity: 'moderate',
    tags: ['xhosa', 'cultural', 'clicks', 'storytelling'],
    popularity: 4,
  },
  {
    id: 'regional_limpopo_venda',
    name: 'Limpopo Venda Showcase',
    description: 'Venda tonal showcase - slowest swing, deepest tradition.',
    subgenre: 'soulful',
    language: 'venda',
    region: 'limpopo',
    gaspType: 'echo',
    gaspIntensity: 'subtle',
    tags: ['venda', 'tonal', 'traditional', 'slow'],
    popularity: 3,
  },

  // === CROSS-CULTURAL FUSIONS ===
  {
    id: 'fusion_zulu_xhosa_gauteng',
    name: 'Zulu-Xhosa Gauteng Fusion',
    description: 'Zulu swing with Xhosa click influence - cultural bridge.',
    subgenre: 'vocal',
    language: 'zulu',
    region: 'gauteng_jhb',
    gaspType: 'double',
    gaspIntensity: 'moderate',
    tags: ['fusion', 'zulu', 'xhosa', 'cultural'],
    popularity: 4,
  },
  {
    id: 'fusion_sotho_tswana_free_state',
    name: 'Sotho-Tswana Free State Fusion',
    description: 'Sotho and Tswana blend - central SA cultural harmony.',
    subgenre: 'soulful',
    language: 'sotho_south',
    region: 'free_state',
    gaspType: 'progressive',
    gaspIntensity: 'moderate',
    tags: ['fusion', 'sotho', 'tswana', 'harmony'],
    popularity: 3,
  },
  {
    id: 'fusion_english_afrikaans_cape',
    name: 'English-Afrikaans Cape Fusion',
    description: 'Western Cape bilingual fusion - modern South Africa.',
    subgenre: 'private_school',
    language: 'english_sa',
    region: 'western_cape',
    gaspType: 'selective',
    gaspIntensity: 'light',
    tags: ['fusion', 'bilingual', 'modern', 'cape-town'],
    popularity: 4,
  },
  {
    id: 'fusion_venda_tsonga_limpopo',
    name: 'Venda-Tsonga Limpopo Fusion',
    description: 'Northern SA fusion - tonal meets relaxed swing.',
    subgenre: 'soulful',
    language: 'venda',
    region: 'limpopo',
    gaspType: 'echo',
    gaspIntensity: 'moderate',
    tags: ['fusion', 'venda', 'tsonga', 'northern'],
    popularity: 3,
  },
  {
    id: 'fusion_ndebele_swazi_mpumalanga',
    name: 'Ndebele-Swazi Mpumalanga Fusion',
    description: 'Eastern SA fusion - clicks meet rural groove.',
    subgenre: 'vocal',
    language: 'ndebele',
    region: 'mpumalanga',
    gaspType: 'half_bar',
    gaspIntensity: 'moderate',
    tags: ['fusion', 'ndebele', 'swazi', 'rural'],
    popularity: 3,
  },

  // === MODERN INNOVATIONS ===
  {
    id: 'modern_gauteng_afrotech',
    name: 'Gauteng Afro-Tech Piano',
    description: 'JHB sound meets Afro-tech - modern innovation.',
    subgenre: 'experimental',
    language: 'english_sa',
    region: 'gauteng_jhb',
    gaspType: 'stutter',
    gaspIntensity: 'heavy',
    tags: ['afro-tech', 'modern', 'innovative', 'electronic'],
    popularity: 4,
  },
  {
    id: 'modern_cape_town_electronica',
    name: 'Cape Town Electronica-Piano',
    description: 'Western Cape electronica fusion - straight swing innovation.',
    subgenre: 'experimental',
    language: 'afrikaans',
    region: 'western_cape',
    gaspType: 'reverse',
    gaspIntensity: 'full',
    tags: ['electronica', 'modern', 'cape-town', 'innovative'],
    popularity: 3,
  },
  {
    id: 'modern_kzn_trap_piano',
    name: 'KZN Trap-Piano Fusion',
    description: 'Durban trap meets Amapiano - genre-defying energy.',
    subgenre: 'experimental',
    language: 'zulu',
    region: 'kzn_durban',
    gaspType: 'buildup',
    gaspIntensity: 'full',
    tags: ['trap', 'fusion', 'durban', 'energetic'],
    popularity: 4,
  },
  {
    id: 'modern_gauteng_jazz_fusion',
    name: 'Gauteng Modern Jazz-Piano',
    description: 'JHB jazz fusion - sophisticated and contemporary.',
    subgenre: 'private_school',
    language: 'english_sa',
    region: 'gauteng_jhb',
    gaspType: 'selective',
    gaspIntensity: 'light',
    tags: ['jazz', 'modern', 'sophisticated', 'fusion'],
    popularity: 4,
  },
  {
    id: 'modern_pretoria_rnb_piano',
    name: 'Pretoria R&B-Piano Fusion',
    description: 'Pretoria R&B influence - smooth and modern.',
    subgenre: 'soulful',
    language: 'english_sa',
    region: 'gauteng_pretoria',
    gaspType: 'progressive',
    gaspIntensity: 'subtle',
    tags: ['rnb', 'modern', 'smooth', 'pretoria'],
    popularity: 4,
  },
];

// Helper functions
export function getPresetsBySubgenre(subgenre: string): CulturalPreset[] {
  return CULTURAL_PRESETS.filter(p => p.subgenre === subgenre);
}

export function getPresetsByLanguage(language: string): CulturalPreset[] {
  return CULTURAL_PRESETS.filter(p => p.language === language);
}

export function getPresetsByRegion(region: string): CulturalPreset[] {
  return CULTURAL_PRESETS.filter(p => p.region === region);
}

export function getPresetsByPopularity(minStars: number = 4): CulturalPreset[] {
  return CULTURAL_PRESETS.filter(p => p.popularity >= minStars).sort((a, b) => b.popularity - a.popularity);
}

export function searchPresets(query: string): CulturalPreset[] {
  const lowerQuery = query.toLowerCase();
  return CULTURAL_PRESETS.filter(p => 
    p.name.toLowerCase().includes(lowerQuery) ||
    p.description.toLowerCase().includes(lowerQuery) ||
    p.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  );
}

export function getPresetById(id: string): CulturalPreset | undefined {
  return CULTURAL_PRESETS.find(p => p.id === id);
}

export const SUBGENRES = ['soulful', 'sgija', 'bacardi', 'private_school', 'vocal', 'deep', 'experimental'] as const;
